apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: easyshop-ingress
  namespace: easyshop-ns
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    # REMOVED: ssl-redirect (won't work without a domain/TLS)
spec:
  rules:
  - http: # No 'host:' line here
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: easyshop-svc
            port:
              number: 80
